### ISSUE TITLE
Cannot write p2diff to file

### ISSUE THREAD

**Issue by mickaelistria** [irbull/p2diff#10]
Currently, p2diff is only printed to System.out. It would be very useful to also have it on a file (configured with some --output=" flag.

**Comment by mickaelistria** [comment]
cc @nickboldt

**Comment by nickboldt** [comment]
Just use `| tee p2diff.log.txt` to pipe to a file.

**Comment by mickaelistria** [comment]
I plan to use p2diff in non-bash context (Tycho eclipserun plugin) where tee isn't easily available.

**Comment by mickaelistria** [comment]
Closed in favour of PR #11
